'''
Export template for Free Texture Packer https://github.com/odrick/free-tex-packer

{
    {{#rects}}
    "{{{name}}}": {
        "x": {{frame.x}},
        "y": {{frame.y}},
        "w": {{frame.w}},
        "h": {{frame.h}}
    }{{^last}},{{/last}}
    {{/rects}}
}

Then run this script on the json generated by FTP to create the json format that the game uses
'''

import json

with open('packed2/characters.json') as f:
    data = json.load(f)

result = {}

for key, value in data.items():
    parts = key.split('/')
    if len(parts) == 3:
        top, mid, last = parts
        if top not in result:
            result[top] = {}
        if mid not in result[top]:
            result[top][mid] = {}
        result[top][mid][last] = value
    else:
        print(f"Malformed: {key}")

for top, top_v in result.items():
    for mid, mid_v in top_v.items():
        arr = [v for v in mid_v.values()]
        top_v[mid] = arr

with open('packed2/characters_out.json', 'w') as f:
    json.dump(result, f, indent=4)